openapi: 3.0.0
info:
  title: View Train Location API Testing
  description: API documentation for Train Management System - COBSCCOMP221P-008
  version: 1.0.0
servers:
  - url: http://localhost:5000 

paths:
  /web/train/get:
    get:
      summary: Get all train locations
      tags:
        - Train
      responses:
        200:
          description: A list of train locations
        500:
          description: Server Error

  /web/train/get/{id}:
    get:
      summary: Get a train by ID
      tags:
        - Train
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The train ID
      responses:
        200:
          description: Details of a specific train
        500:
          description: Server Error

  /web/train/create:
    post:
      summary: Add a new train
      tags:
        - Train
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Train'
      responses:
        201:
          description: Train created successfully
        400:
          description: Validation Error
        500:
          description: Server Error

  /web/train/train/{id}:
    put:
      summary: Update a train by ID
      tags:
        - Train
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The train ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Train'
      responses:
        200:
          description: Train updated successfully
        400:
          description: Validation Error
        404:
          description: Train not found
        500:
          description: Server Error

  /web/train/deleteTrain/{id}:
    delete:
      summary: Delete a train by ID
      tags:
        - Train
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The train ID
      responses:
        200:
          description: Train deleted successfully
        404:
          description: Train not found
        500:
          description: Server Error

  # User Routes
  /web/user/users:
    get:
      summary: Get all users
      tags:
        - User
      responses:
        200:
          description: A list of users
        500:
          description: Server Error

  /web/user/register:
    post:
      summary: Register a new user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: User registered successfully
        400:
          description: Validation Error
        500:
          description: Server Error

  /web/user/login:
    post:
      summary: User login
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        200:
          description: User logged in successfully
        400:
          description: Invalid email or password
        500:
          description: Server Error

  /web/user/users/{id}:
    put:
      summary: Update a user by ID
      tags:
        - User
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The user ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: User updated successfully
        404:
          description: User not found
        500:
          description: Server Error

  /web/user/admin/users/{id}:
    put:
      summary: Update an admin user by ID
      tags:
        - User
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The admin user ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: Admin user updated successfully
        404:
          description: Admin user not found
        500:
          description: Server Error

  /web/user/delusers/{id}:
    delete:
      summary: Delete a user by ID
      tags:
        - User
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The user ID
      responses:
        200:
          description: User deleted successfully
        404:
          description: User not found
        500:
          description: Server Error

  /web/user/admin/delusers/{id}:
    delete:
      summary: Delete an admin user by ID
      tags:
        - User
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The admin user ID
      responses:
        200:
          description: Admin user deleted successfully
        404:
          description: Admin user not found
        500:
          description: Server Error

components:
  schemas:
    Train:
      type: object
      properties:
        trainId:
          type: string
        trainName:
          type: string
        location:
          type: string
        lat:
          type: number
        lon:
          type: number
        speed:
          type: number
        capacity:
          type: number

    User:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string

    UserLogin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
